import {
  antdesign,
  boot,
  bootstrap,
  ci,
  express,
  firebase,
  flutter,
  js,
  mongo,
  mySql,
  nest,
  next,
  nuxt,
  postgresql,
  react,
  redux,
  tailwind,
  vue,
} from "../../../public/icon";
import {
  book,
  bookshelf,
  bountie,
  dans,
  dansSoc,
  disney,
  hidden,
  kulineran,
  marvel,
  medeasy,
  movielist,
  portal,
  prayer,
  qleap,
  qleapMobile,
  showhun,
  task,
  trvl,
  warteg,
} from "../../../public/images/homePage";

export const projects = {
  all: [
    {
      name: `DaneBooking`,
      photo: book,
      desc: `This is a fullstack website that i built after learning mern stack from LamaDev, you can book your hotel room and choose which date you want to book`,
      github: `https://github.com/mhmddzidane/DaneBook`,
      tech: [react, express, mongo],
      category: `mern`,
      id: 2,
    },
    {
      name: `Movie List`,
      photo: movielist,
      desc: `This project was made using movie api`,
      github: `https://github.com/mhmddzidane/Movie-List`,
      tech: [js],
      category: `html`,
      id: 3,
    },
    {
      name: `Bookshelf App`,
      photo: bookshelf,
      desc: `Submission belajar fundamental web Dicoding`,
      github: `https://github.com/mhmddzidane/ToReadBookApps`,
      tech: [js],
      category: "html",
      id: 4,
    },
    {
      name: `Prayer Times`,
      photo: prayer,
      desc: `Prayer Times based on user location, using api from https://aladhan.com/prayer-times-api`,
      github: `https://github.com/mhmddzidane/Prayer-Times`,
      tech: [js],
      category: "html",
      id: 5,
    },
    {
      name: `Portal Beritaku`,
      photo: portal,
      desc: `Website Portal Berita dengan ReactJS diambil dari API https://newsapi.org/`,
      github: `https://github.com/mhmddzidane/PortalBeritaku`,
      tech: [react],
      category: "react",
      id: 6,
    },
    {
      name: `Warteg 4.0`,
      photo: warteg,
      desc: `Exercise project built with React js and Jsonplaceholder fake api`,
      github: `https://github.com/mhmddzidane/Warteg-4.0`,
      tech: [react, boot],
      category: "react",
      id: 7,
    },
    {
      name: `DANS`,
      photo: dans,
      desc: `Projek latihan fullstack web online store`,
      github: `https://github.com/mhmddzidane/dans-fashion-store`,
      demo: `https://dans-fashion-store.vercel.app/`,
      tech: [react, express, mongo, redux],
      category: "mern",
      id: 8,
    },
    {
      name: `Disney+ Clone`,
      photo: disney,
      desc: `Projek latihan cloning web disney+ dengan api https://www.themoviedb.org/`,
      github: `https://github.com/mhmddzidane/DisneyPlusClone`,
      demo: `https://disney-plus-clone-eight-rosy.vercel.app/`,
      tech: [next, tailwind],
      category: "react",
      id: 9,
    },
    {
      name: `MARVEL WIKI`,
      photo: marvel,
      desc: `Website to find information about marvel universe (in development)`,
      github: `https://github.com/mhmddzidane/marvel-wiki`,
      demo: `https://marvel-wiki-lyart.vercel.app/`,
      tech: [next, tailwind],
      category: "react",
      id: 10,
    },
    {
      name: `Dans Social`,
      photo: dansSoc,
      desc: `Fullstack social media website, you can post,comment,and like and also follow your friends. (in development)`,
      github: `https://github.com/mhmddzidane/Dans-Social`,
      tech: [react, express, mySql],
      category: "mern",
      id: 11,
    },
    {
      name: `Hidden Gem`,
      photo: hidden,
      desc: `Project Matakuliah pemrogman smartweb, top 10 finalist pameran hasil karya mahasiswa fakultas ilmu komputer`,
      github: `https://github.com/mhmddzidane/HiddenGem`,
      demo: `https://gemshidden.000webhostapp.com/`,
      tech: [ci, mySql, boot],
      category: "php",
      id: 12,
    },
    {
      name: `Kulineran`,
      photo: kulineran,
      desc: `Vuejs and Vuex learning projects, users can see food, search for food, and put food in baskets, and complete orders. Built using the fake Jsonplaceholder api`,
      github: `https://github.com/mhmddzidane/kulineran`,
      tech: [vue, boot],
      category: "vue",
      id: 13,
    },
    {
      name: `Task Board`,
      photo: task,
      desc: `Nuxtjs and Vuex learning projects, user can insert task, change it to done, and delete it`,
      github: `https://github.com/mhmddzidane/nuxt-todo`,
      tech: [nuxt],
      category: "vue",
      id: 14,
    },
    {
      name: `TVShowhun`,
      photo: showhun,
      desc: `TV show information website, you can find the information about tv show such as synopsis,cast,episodes, etc.`,
      github: `https://github.com/mhmddzidane/tvshowvue`,
      demo: `https://tvshowvue.vercel.app/`,
      tech: [vue, tailwind],
      category: "vue",
      id: 15,
    },
    {
      name: `Qleap`,
      photo: qleap,
      desc: `Qleap is an innovative internal HRIS application designed for all Erajaya employees. Packed with a wide range of features, Qleap empowers employees to thrive in their roles. One standout feature is the *Weekly Quiz*, which challenges and sharpens employees' knowledge about products and their respective roles. Additionally, Qleap offers seamless access to employee services such as employee loan, status promotions, and approvals for various employee submissions. It's more than just an HR tool—Qleap is a dynamic platform that drives engagement, productivity, and growth within the Erajaya team. `,
      github: ``,
      demo: `https://qleap.erajaya.com/`,
      tech: [react, bootstrap],
      category: "react",
      id: 16,
    },
    {
      name: `Qleap Mobile`,
      photo: qleapMobile,
      desc: `Qleap Mobile is an innovative internal HRIS application designed for all Erajaya employees. Packed with a wide range of features, Qleap empowers employees to thrive in their roles. One standout feature is the *Weekly Quiz*, which challenges and sharpens employees' knowledge about products and their respective roles. Additionally, Qleap offers seamless access to employee services such as employee loan, status promotions, and approvals for various employee submissions. It's more than just an HR tool—Qleap is a dynamic platform that drives engagement, productivity, and growth within the Erajaya team. `,
      github: ``,
      demo: `https://play.google.com/store/apps/details?id=hcdigital.erajaya.qleap&hl=id`,
      tech: [flutter, firebase],
      category: "flutter",
      id: 17,
    },
    {
      name: `Medasy WebApp`,
      photo: medeasy,
      desc: `Medeasy is a cutting-edge doctor consultation app that redefines healthcare accessibility. Offering a range of services, users can connect with doctors via video calls or chat for personalized consultations. With the flexibility to book appointments with their preferred doctors, users enjoy a seamless healthcare experience. Plus, Medeasy rewards every completed consultation with points, making healthcare not just easy but also rewarding!`,
      github: ``,
      demo: `https://medeasy.ph/`,
      tech: [react, antdesign, nest, postgresql],
      category: "react",
      id: 18,
    },
    {
      name: `Bountie WebApp`,
      photo: bountie,
      desc: `Bountie is an esports platform designed for gamers to showcase their skills and compete for rewards. On Bountie, users can participate in a variety of game tournaments, whether individually or as a team, with the chance to win points that can be converted into cash. Additionally, Bountie features live streams of popular games, creating a hub for both competition and entertainment. It’s the ultimate destination for gamers to play, compete, and thrive!`,
      github: ``,
      demo: `https://www.bountie.io/`,
      tech: [react, tailwind],
      category: "react",
      id: 19,
    },
  ],
};
